import type { PlaneDesign } from './types';

// Representative one-sheet configurations, not measurements of named designs.
// Geometry is projected flying geometry; aerodynamic coefficients are estimates.
// Every aircraft uses the same uncut A4 sheet at 80 g/m²: 0.210 × 0.297 × 80 / 1000 kg.
const A4_MASS = 0.0049896;

export const DESIGNS: PlaneDesign[] = [
  {
    id: 'classic-dart',
    name: 'Classic Dart',
    category: 'Dart',
    subtitle: 'A sharp, steady classic',
    description: 'A pointed nose, deep center keel, and narrow wings favor a firm launch. Its small wing area gives it a higher wing loading than the broad gliders.',
    color: '#ee896f',
    shape: 'dart',
    mass: A4_MASS,
    wingArea: 0.0128,
    span: 0.154,
    length: 0.279,
    cd0: 0.035,
    liftSlope: 2.6,
    maxCl: 0.82,
    trimAngle: 4.3,
    stability: 0.88,
    dihedral: 5,
    foldSteps: [
      'Start with an A4 sheet in portrait orientation. Fold it lengthwise in half, crease, and reopen.',
      'Fold the two top corners inward so their edges meet the center crease.',
      'Fold the new sloping edges inward to the center again, making a long pointed nose.',
      'Fold the plane in half along the center crease with the folded layers on the outside.',
      'Fold each wing downward, keeping a center keel about 2 cm deep and matching the two wing edges.',
      'Open the wings so their tips sit a little higher than their roots. Keep the nose and both wings symmetrical.',
    ],
  },
  {
    id: 'nakamura-lock',
    name: 'Nakamura Lock',
    category: 'Locked glider',
    subtitle: 'Folded for balance',
    description: 'A folded nose tab locks the layers together while broad wings and a modest keel support a stable glide. The extra nose layers shift the balance forward.',
    color: '#91bdeb',
    shape: 'nakamura',
    mass: A4_MASS,
    wingArea: 0.0202,
    span: 0.241,
    length: 0.218,
    cd0: 0.042,
    liftSlope: 3.25,
    maxCl: 1.04,
    trimAngle: 5.5,
    stability: 0.91,
    dihedral: 7,
    foldSteps: [
      'With the A4 sheet in portrait orientation, make a lengthwise center crease and reopen.',
      'Fold the top corners to the center crease to make a triangular nose.',
      'Fold the whole nose downward across the base of that triangle, making an envelope-shaped top.',
      'Fold the new top corners inward toward the center, leaving a small triangular tip exposed beneath them.',
      'Fold that exposed tip upward over the two corner folds to lock them in place.',
      'Fold the sheet in half along the center crease with the locking tab on the outside.',
      'Fold two broad matching wings down, leaving a keel about 1.5 cm deep, then raise the wing tips slightly.',
    ],
  },
  {
    id: 'wide-glider',
    name: 'Wide Glider',
    category: 'Glider',
    subtitle: 'Room to catch the air',
    description: 'Broad, nearly rectangular wings reduce wing loading and suit a gentle release. A shallow center keel and raised tips help it settle into a glide.',
    color: '#91cdb4',
    shape: 'wide',
    mass: A4_MASS,
    wingArea: 0.0234,
    span: 0.284,
    length: 0.173,
    cd0: 0.046,
    liftSlope: 3.55,
    maxCl: 1.1,
    trimAngle: 5.2,
    stability: 0.85,
    dihedral: 8,
    foldSteps: [
      'Turn the A4 sheet to landscape orientation. Fold it across the middle to mark the nose-to-tail centerline, then reopen.',
      'Fold the two corners of one long edge inward to the centerline, making a broad triangular nose.',
      'Fold the nose tip back about 3 cm to make a blunt, layered leading edge.',
      'Fold the sheet in half along its centerline with the nose folds on the outside.',
      'Fold each wing down parallel to the centerline, leaving a narrow keel about 1 cm deep.',
      'Open the wide wings and lift their tips evenly. Keep the trailing edges straight before adding any trim.',
    ],
  },
  {
    id: 'delta-wing',
    name: 'Delta Wing',
    category: 'Swept wing',
    subtitle: 'A clean triangular planform',
    description: 'Swept leading edges and a compact triangular wing offer a balance between the dart and the broad gliders. Symmetrical folds matter to its straight flight.',
    color: '#e7b968',
    shape: 'delta',
    mass: A4_MASS,
    wingArea: 0.0191,
    span: 0.211,
    length: 0.243,
    cd0: 0.038,
    liftSlope: 2.95,
    maxCl: 0.96,
    trimAngle: 4.8,
    stability: 0.8,
    dihedral: 4,
    foldSteps: [
      'Place an A4 sheet in portrait orientation, crease it lengthwise in half, and reopen.',
      'Fold both top corners to the centerline to form a pointed nose.',
      'Fold each sloping leading edge toward the centerline, stopping short of the center so the nose stays broad.',
      'Fold a small part of the pointed tip inward to reinforce the nose.',
      'Fold the sheet in half along the centerline with the nose layers outside.',
      'Fold the wings down along matching lines that run from the nose toward the rear corners, leaving a slim center keel.',
      'Spread the triangular wings and raise both tips slightly; flatten any twist along the swept leading edges.',
    ],
  },
  {
    id: 'condor',
    name: 'Condor',
    category: 'Broad glider',
    subtitle: 'Long wings, soft release',
    description: 'Long wings with small upright tips provide a broad lifting surface. A rolled front fold adds nose weight, while the raised tips help the wings resist uneven handling.',
    color: '#b3c981',
    shape: 'glider',
    mass: A4_MASS,
    wingArea: 0.0242,
    span: 0.292,
    length: 0.184,
    cd0: 0.049,
    liftSlope: 3.6,
    maxCl: 1.12,
    trimAngle: 5.8,
    stability: 0.82,
    dihedral: 10,
    foldSteps: [
      'Lay an A4 sheet in landscape orientation. Mark the nose-to-tail centerline by folding across the middle and reopening.',
      'Fold one long edge down about 1.5 cm, then fold that strip over once more to make a weighted straight nose.',
      'Fold the two nose corners inward as small matching triangles to soften the front corners.',
      'Fold the sheet in half along the centerline with the weighted nose layers outside.',
      'Fold broad wings down parallel to the centerline, leaving a center keel about 1 cm deep.',
      'Fold a narrow strip at each wing tip upward to make matching small fins.',
      'Open the wings and give them a gentle upward V. Check that both tip fins stand at the same angle.',
    ],
  },
  {
    id: 'needle',
    name: 'Needle',
    category: 'Narrow dart',
    subtitle: 'Slim and fast to launch',
    description: 'A very narrow wing and long reinforced nose concentrate the sheet into a slender dart. It needs more airspeed to support its weight than the larger-wing designs.',
    color: '#b19bd8',
    shape: 'needle',
    mass: A4_MASS,
    wingArea: 0.0104,
    span: 0.12,
    length: 0.287,
    cd0: 0.031,
    liftSlope: 2.3,
    maxCl: 0.74,
    trimAngle: 4,
    stability: 0.9,
    dihedral: 3,
    foldSteps: [
      'Start with an A4 sheet in portrait orientation. Make a lengthwise center crease and reopen.',
      'Fold both top corners to the centerline.',
      'Fold the two sloping edges inward to the centerline again to make a longer nose.',
      'Fold the new outer sloping edges inward once more, keeping both sides aligned.',
      'Fold the plane in half along the centerline with the folded layers outside.',
      'Fold two narrow wings downward, leaving a deep center keel and matching the rear corners.',
      'Spread the wings just above level. Keep both leading edges straight and use only a very small trailing-edge trim.',
    ],
  },
  {
    id: 'canard',
    name: 'Canard',
    category: 'Foreplane',
    subtitle: 'A little lift up front',
    description: 'Small forward tabs sit ahead of the main wings. This representative canard has a layered nose and more profile drag, with trim that is sensitive to the foreplane angle.',
    color: '#d997b4',
    shape: 'canard',
    mass: A4_MASS,
    wingArea: 0.0205,
    span: 0.239,
    length: 0.202,
    cd0: 0.054,
    liftSlope: 3.15,
    maxCl: 1.05,
    trimAngle: 6,
    stability: 0.71,
    dihedral: 6,
    foldSteps: [
      'With an A4 sheet in portrait orientation, make a lengthwise center crease and reopen.',
      'Fold both top corners inward to the centerline to form a triangular nose.',
      'Fold the pointed nose downward across the base of the triangle, leaving the nose layers accessible.',
      'Fold the new top corners inward partway, leaving two matching short triangular tabs at the front.',
      'Fold the plane in half along the centerline with those front tabs on the outside.',
      'Fold the large rear wings down, starting the wing creases behind the front tabs and leaving a small center keel.',
      'Open the front tabs outward as two small foreplanes, keeping their size and angle equal.',
      'Open the main wings into a gentle upward V. Adjust the front tabs by tiny equal amounts when trimming.',
    ],
  },
  {
    id: 'swallow',
    name: 'Swallow',
    category: 'Stunt glider',
    subtitle: 'Responsive to a little trim',
    description: 'Swept wings and folded rear tips make a responsive glider. Lower modeled stability lets launch angle and trim change its path more strongly than the locked designs.',
    color: '#78bec8',
    shape: 'stunt',
    mass: A4_MASS,
    wingArea: 0.0174,
    span: 0.226,
    length: 0.224,
    cd0: 0.059,
    liftSlope: 3.2,
    maxCl: 1,
    trimAngle: 6.2,
    stability: 0.58,
    dihedral: 3,
    foldSteps: [
      'Place an A4 sheet in portrait orientation, crease it lengthwise in half, and reopen.',
      'Fold the top corners to the centerline to make a triangular nose.',
      'Fold the nose tip downward about 4 cm to reinforce it and shorten the point.',
      'Fold the outer nose edges inward once more, keeping the left and right folds symmetrical.',
      'Fold the plane in half along the centerline and fold two broad swept wings down, leaving a small keel.',
      'Fold each rear outer corner upward as a small matching triangular wingtip, giving the back corners an angled silhouette.',
      'Open the wings almost level. Start with straight trailing edges, then add tiny equal upward trim folds for a looping tendency.',
    ],
  },
];

export function getDesign(id: string): PlaneDesign {
  const design = DESIGNS.find((candidate) => candidate.id === id);
  if (!design) throw new Error(`Unknown paper plane design: ${id}`);
  return design;
}
